### ISSUE TITLE
SendBirdUser model deserialize fails when session token present in response

### ISSUE THREAD

**Issue by sk-hasbridge** [sendbird/sendbird-platform-sdk-php#4]
I am attempting to issue a session token for a user by calling the `updateUserById` method on the User API, with `setIssueSessionToken(true)`. This fails with the error `Object of class stdClass could not be converted to string`. Here's a simplified version of the calling code:
```
$data = new UpdateUserByIdData();
$data->setUserId($id)
    ->setNickname('John Doe')
    ->setProfileUrl('http://example.org/profile.jpg')
    ->setIssueSessionToken(true);

$userApiClient = new UserApi(
    new GuzzleClient,
    Configuration::getDefaultConfiguration()->setHost('<my request url>')
);
$response = $userApiClient->updateUserById('<my api token>', 123, $data);
```

And here's the exception:
```
Object of class stdClass could not be converted to string

  at vendor/sendbird/sendbird-platform-sdk-php/lib/ObjectSerializer.php:445
    441▕         }
    442▕
    443▕         /** @psalm-suppress ParadoxicalCondition */
    444▕         if (in_array($class, ['\DateTime', '\SplFileObject', 'array', 'bool', 'boolean', 'byte', 'double', 'float', 'int', 'integer', 'mixed', 'number', 'object', 'string', 'void'], true)) {
  ➜ 445▕             settype($data, $class);
    446▕             return $data;
    447▕         }
    448▕
    449▕
```

After doing some debugging and inspecting which field it's actually failing on, it turned out to be the `session_tokens` property on the response. In `lib/Model/SendBirdUser.php` it's defined as `string[]` in `$openAPITypes`, but in the response it's an array of objects instead. 

It also doesn't appear that the library supports the newer session token endpoint at `/users/{user_id}/token`, so I haven't found a workaround.

**Comment by james-a-rob** [comment]
Hi @sk-hasbridge 

I have released a new version of the SDK with support for the /user/{user_id}/token endpoint

https://github.com/sendbird/sendbird-platform-sdk-php/releases/tag/1.0.11

**Comment by sk-hasbridge** [comment]
Awesome, thanks for the quick update!
